[username]
show_always = true
format = "[$user]($style)@"

[hostname]
ssh_only = false
trim_at =	""
format = "[$hostname]($style) "

[directory]
truncate_to_repo=false

[git_branch]
format = "on [$branch]($style) "

[package]
format = "[$symbol$version]($style) "

[cmd_duration]
disabled = true
