[theme]
name = "native"

[icons]
name = "awesome"

[[block]]
block = "custom"
interval = 180
command = "exec ~/.config/scripts/plucky-girl.fish"
json = true

[[block]]
block = "weather"
format = "{weather} {temp}"
service = { name = "openweathermap", city_id = "5746545", units = "imperial" }
on_click= "firefox --new-window https://openweathermap.org/city/5746545"
if_command = "test $OPENWEATHERMAP_API_KEY"

[[block]]
block = "hueshift"
hue_shifter = "wlsunset"
step = 100
click_temp = 3500

[[block]]
block = "networkmanager"
on_click = "kitty nmtui"
device_format = "{icon}{ap}"
interface_name_exclude = ["virbr", "docker"]

[[block]]
block = "disk_space"
format = " {used}"
path = "/"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
format = "{percentage}"
hide_missing = true

[[block]]
block = "time"
interval = 5
format = "%a %m/%d %R"
