[theme]
name = "native"

[icons]
name = "awesome"

# [[block]]
# block = "pomodoro"
# length = 25
# break_length = 5
# notifier = "swaynag"
# message = "Take a break!"
# break_message = "Back to work!"

[[block]]
block = "weather"
format = "{weather} {temp}"
service = { name = "openweathermap", city_id = "5746545", units = "imperial" }

[[block]]
block = "networkmanager"
on_click = "kitty nmtui"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
format = "{percentage}"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
