[theme]
name = "native"

[icons]
name = "awesome"

[[block]]
block = "weather"
format = "{weather} {temp}"
service = { name = "openweathermap", city_id = "5746545", units = "imperial" }
on_click= "firefox --new-window https://openweathermap.org/city/5746545"
if_command = "ping -W 1 -c 1 8.8.8.8 && test $OPENWEATHERMAP_API_KEY"

[[block]]
block = "custom"
command = "if [[ $(nordvpn settings | grep 'Kill Switch: enabled') ]]; then echo KS; else echo XX; fi"
on_click = "/home/stel/.config/scripts/nordvpn-toggle-killswitch.sh"
interval = 5

[[block]]
block = "networkmanager"
on_click = "kitty nmtui"
device_format = "{icon}{ap}"
interface_name_exclude = ["virbr", "docker"]

[[block]]
block = "disk_space"
format = " {used}"
path = "/"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
format = "{utilization} {frequency}"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
format = " {percentage}"
# Not working for some reason
hide_missing = true
if_command = "test -e /sys/class/power_supply/BAT0 || test -e /sys/class/power_supply/BAT1"

[[block]]
block = "time"
interval = 5
format = "%a %m/%d %I:%M %p"
