#! /usr/bin/env bash

sudo dnf install \
neovim bash bash-completion fish starship git tree bat fd-find ripgrep wget neofetch curl htop jq tldr unzip rsync restic trash-cli \
google-noto-sans-mono google-noto-emoji-color-fonts fontawesome-fonts \
make g++ clojure rust cargo nodejs fennel racket lua \
firefox kitty keepassxc dolphin torbrowser-launcher \
sway mako xdg-desktop-portal-wlr slurp wl-clipboard wtype libinput-tools grim  wofi \
i3 setxkbmap rofi slop maim feh \
kvantum qt5ct gammastep brightnessctl \
wireplumber
