#!/usr/bin/env bash

repo="$@"

if [[ -e $repo ]]; then
  restic backup --files-from ~/.config/restic/include.txt --exclude-file ~/.config/restic/exclude.txt --repo "$@"
else
  echo "ERROR: Enter a valid repo path"
  exit 1
fi
