# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# save commands immediately
export PROMPT_COMMAND='history -a'

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=3000
HISTFILESIZE=5000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

pathadd() {
  if [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]]; then
    PATH="${PATH:+"$PATH:"}$1"
  fi
}
# These nix path additions shouldn't be necessary because of /etc/profile.d/nix
pathadd "/nix/var/nix/profiles/default/bin" # Nix packages installed by root user
pathadd "$HOME/.nix-profile/bin"
pathadd "$HOME/.local/bin"
pathadd "$HOME/.cargo/bin"
pathadd "$HOME/go/bin"

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# Colorize man pages
export LESS_TERMCAP_mb=$(printf "\e[1;31m")
export LESS_TERMCAP_md=$(printf "\e[1;33m")
export LESS_TERMCAP_me=$(printf "\e[0m")
export LESS_TERMCAP_se=$(printf "\e[0m")
export LESS_TERMCAP_so=$(printf "\e[01;48;5;4;38;5;0m")
export LESS_TERMCAP_ue=$(printf "\e[0m")
export LESS_TERMCAP_us=$(printf "\e[0;35m")
export MANPAGER='less -s -M +Gg'

# some more ls aliases
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'
# Debian installs batcat, Fedora installs bat
if command -v batcat; then
  alias bat='batcat --theme=base16 --plain'
else
  alias bat='bat --theme=base16 --plain'
fi
alias gs='git status'
alias gl='git fancy-log'
alias glo='git log --oneline'
alias rm='rm -i'
alias mv='mv -n'
alias t='tmux attach -t config || tmux'
alias beep="aplay --quiet ~/music/sound-effects/ding-ding.wav"
alias alert='notify-send "Terminal alert! 🐢"'
alias cp="cp -n"
if command -v fdfind &> /dev/null; then
  alias fd="fdfind"
fi
# Like startx, start wayland, qt setting
alias startw="exec ~/.config/scripts/start-sway.sh"

export BROWSER="firefox"
export EDITOR="nvim"
# i3status-rs uses this API key for the weather block
if [ -e ~/secrets/openweathermap-api-key ]; then
  export OPENWEATHERMAP_API_KEY=`cat ~/secrets/openweathermap-api-key`
fi
# Theoretically cool but I always accidentally trigger vi mode by pressing escape when typing
# set -o vi
set -o noclobber
# Let qt5ct handle qt theming
export QT_QPA_PLATFORMTHEME=qt5ct

# Allow Nix to install unfree packages
export NIXPKGS_ALLOW_UNFREE=1

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

eval "$(starship init bash)"

